# Generated by Django 5.1.1 on 2024-09-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessevent',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='chessevent',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
